const CONST = {
    WINDOW_HEIGHT: 600,
    WINDOW_WIDTH: 400,
    SUPABASE_URL: 'https://yitbtnrvtvqsevxgddsg.supabase.co',
    SUPABASE_PUBLIC_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpdGJ0bnJ2dHZxc2V2eGdkZHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTQ0MTY4MDcsImV4cCI6MTk2OTk5MjgwN30.wEkIXs5ZY4lRH_MUO5DMNfDEwPXgkWVKrxKd0JeDR7o',
};

export default CONST;
